services:
  postgres:
    image: postgres:16-alpine
    container_name: destiny-db
    environment:
      POSTGRES_DB: destiny
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"
